name: Fetch Wikipedia Edits

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Debug - List files in repository
        run: ls -al

      - name: Debug - Check Python version
        run: python --version

      - name: Debug - Install dependencies
        run: pip install requests

      - name: Debug - Run script
        run: |
          echo "Running fetch_wikipedia_data.py"
          python fetch_wikipedia_data.py
          echo "Script completed"

      - name: Debug - List files in data directory
        run: ls -al data

      - name: Commit and push data
        run: |
          echo "Starting commit process"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add data/
          git commit -m "Update Wikipedia data"
          git push
          echo "Commit and push completed"
